### ISSUE TITLE
Add styles for forms and input elements

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/downstyler#5]
One interesting inspiration source could be Baseline.css' form styles: http://stephanecurzi.me/baselinecss.2009/form.html (check how they look in multiple platforms)

The source doesn't appear to be browsable online, but here's the entirety of 0.5.3's `baseline.form.css`: 

``` css
/*
Baseline - a designer framework
Copyright (C) 2009 Stephane Curzi, ProjetUrbain.com
Creative Commons Attribution-Share Alike 3.0 License
version 0.5
*/

/******************** Form ********************/

form                            { overflow: auto; }
legend                          { padding-bottom: 18px; }
label                           { width: 100%; position: relative; top: 5px; margin-bottom: 18px; line-height: 18px; display: block; }

input[type="text"],
input[type="password"],
input[type="select"],
input[type="search"]            { width: 100%; margin-bottom: -1px; display: block; }

input[type="radio"]             { top: -1px; margin: 0 4px 3px 1px; }
input[type="checkbox"]          { top: -2px; margin: 0 4px 3px 1px; }
input[type="file"]              { margin: 0px 6px 3px 6px; }

input[type="submit"],
input[type="reset"],
input[type="button"]            { position: relative; top: 5px; margin-bottom: 18px; }

select                          { display: block; margin: 0px; }
textarea                        { width: 99%; line-height: 18px; margin-bottom: -2px; display: block; clear: left; overflow: auto; }
```
