### ISSUE TITLE
Add styles for aside elements

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/downstyler#50]
Here's an example:

```css
aside {
	float: right;
	background: #def;
	border-left: 1px solid #789;
	width: 50%;
	font-size: 90%;
	padding: 0.5em 1em;
	margin: 0.3em -4em 0px 2em;
}
```

Result, in the "paper-like" mode for [this article](https://www.theverge.com/2020/1/16/21068387/):

![Screenshot 2020-01-16 at 18 40 33](https://user-images.githubusercontent.com/478237/72552974-d0a25600-388f-11ea-8134-921d1a69fd66.png)
