### ISSUE TITLE
Tweak selection color for paperlike style

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/downstyler#52]
As was mentioned in #41. Since then, [::selection](https://caniuse.com/#feat=css-selection) became supported in the major browsers (e.g. it became unprefixed in Firefox in v62, released on 5 Sep 2018), so it should now be safe to use.

Some options:
- A [lemon-lime](https://en.wikipedia.org/wiki/Lime_(color)#Lemon-lime) color resembling the fluorescent yellow of highlighter markers:
  ```css
  ::-moz-selection { background-color: #EF6; }
  ```
- A warmer yellow ([maize](https://en.wikipedia.org/wiki/Maize_(color))), similar to [Gold](https://en.wikipedia.org/wiki/Gold_(color)) but not as dark:
  ```css
  ::-moz-selection { background-color: #FE6; }
  ```
